/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms_app;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author Akarsh
 */
public class update_main extends javax.swing.JFrame {

   
    /**
     * Creates new form update_main
     */
    public update_main() {
       initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pointbtn = new javax.swing.JButton();
        mobilebtn = new javax.swing.JButton();
        namebtn = new javax.swing.JButton();
        res = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pointbtn.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        pointbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms_app/Refresh-icon.png"))); // NOI18N
        pointbtn.setText("Update Points");
        pointbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointbtnActionPerformed(evt);
            }
        });

        mobilebtn.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        mobilebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms_app/Refresh-icon.png"))); // NOI18N
        mobilebtn.setText("Update Mobile");
        mobilebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobilebtnActionPerformed(evt);
            }
        });

        namebtn.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        namebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms_app/Refresh-icon.png"))); // NOI18N
        namebtn.setText("Update Name");
        namebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namebtnActionPerformed(evt);
            }
        });

        res.setFont(new java.awt.Font("Segoe Print", 0, 20)); // NOI18N

        jButton3.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 20)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms_app/back-icon.png"))); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pointbtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mobilebtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(res, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(130, 130, 130))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(namebtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jButton3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(namebtn)
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(res, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(mobilebtn)
                        .addGap(47, 47, 47)))
                .addGap(57, 57, 57)
                .addComponent(pointbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namebtnActionPerformed
        // TODO add your handling code here:
        update_name un = new update_name();
        un.setVisible(true);
        dispose();
    }//GEN-LAST:event_namebtnActionPerformed

    private void mobilebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobilebtnActionPerformed
        // TODO add your handling code here:
        update_mobile um = new update_mobile();
        um.setVisible(true);
        dispose();
    }//GEN-LAST:event_mobilebtnActionPerformed

    private void pointbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointbtnActionPerformed
        // TODO add your handling code here:
        update_point up = new update_point();
        up.setVisible(true);
        dispose();
    }//GEN-LAST:event_pointbtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        main_page mp = new main_page();
        mp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton mobilebtn;
    private javax.swing.JButton namebtn;
    private javax.swing.JButton pointbtn;
    private javax.swing.JLabel res;
    // End of variables declaration//GEN-END:variables
}
